### ISSUE TITLE
classIntervals: 'probs' argument to 'quantile' not allowed as documented

### ISSUE THREAD

**Issue by AMBarbosa** [rsbivand/classInt#1]
Hi,

The `classIntervals` help file says that '_The "quantile" style provides quantile breaks; arguments to quantile may be passed through ..._', but apparently the `probs` argument isn't allowed, as it is already set by `classIntervals`:

```
data_censored<-c(rep(0,10), rnorm(100, mean=20,sd=1),rep(26,10))
plot(density(data_censored))
classIntervals(data_censored, style="quantile", probs = seq(0, 1, 0.25))
# Error in quantile.default(x = var, probs = seq(0, 1, 1/n), ...) : 
#  formal argument "probs" matched by multiple actual arguments
```

I'd suggest documenting this, or else allowing the user to choose the `probs`, even if their default is still `seq(0, 1, 1/n)` (as seen in the `classIntervals` code).

Regards,

**Comment by rsbivand** [comment]
Thanks for a useful report, patch coming.

**Comment by rsbivand** [comment]
By the way, `n` as 4 gives the expected output:
```
> classIntervals(data_censored, style="quantile", n=4)
style: quantile
  one of 166,650 possible partitions of this variable into 4 classes
       [0,19.22306) [19.22306,19.97196) [19.97196,20.69348)       [20.69348,26] 
                 30                  30                  30                  30 
```
I'll try to implement a work-around extracting the integer unique difference from the provided argument.

**Comment by rsbivand** [comment]
This is my original repo - the correct repo is https://github.com/r-spatial/classInt, and the issue there is https://github.com/r-spatial/classInt/issues/49. I've committed a fix to branch `q_probs` there. Please check whether this resolves your problem, which in any case was using `probs` instead of `n`.
